const themePalette = (colors) => {
	return {
		mode: 'light',
		common: {
			black: colors.black,
			white: colors.white,
		},
		primary: {
			main: colors.primaryMain,
			light: colors.primaryLight,
			dark: colors.primaryDark,
			100: colors.primary100,
			contrastText: colors.white,
		},
		secondary: {
			main: colors.secondaryMain,
			light: colors.secondaryLight,
			dark: colors.secondaryDark,
			contrastText: colors.white,
		},
		error: {
			main: colors.errorMain,
			light: colors.errorLight,
			dark: colors.errorDark,
			contrastText: colors.white,
		},
		warning: {
			main: colors.warningMain,
			light: colors.warningLight,
			dark: colors.warningDark,
			contrastText: colors.white,
		},
		info: {
			main: colors.infoMain,
			light: colors.infoLight,
			dark: colors.infoDark,
			contrastText: colors.white,
		},
		success: {
			main: colors.successMain,
			light: colors.successLight,
			dark: colors.successDark,
			contrastText: colors.white,
		},
		white: {
			main: colors.white,
			light: colors.white,
			dark: colors.white,
			contrastText: colors.black,
		},
		black: {
			main: colors.black,
			light: colors.black,
			dark: colors.black,
			contrastText: colors.white,
		},
		grey: {
			50: colors.grey50,
			100: colors.grey100,
			200: colors.grey200,
			300: colors.grey300,
			400: colors.grey400,
			500: colors.grey500,
			600: colors.grey600,
			700: colors.grey700,
			800: colors.grey800,
			900: colors.grey900,
			A100: colors.a100,
			A200: colors.a200,
			A400: colors.a400,
			A700: colors.a700,
		},
		color: {
			red: colors.red,
			orange: colors.orange,
			yellow: colors.yellow,
			green: colors.green,
			teal: colors.teal,
			cyan: colors.cyan,
			blue: colors.blue,
			indigo: colors.indigo,
			purple: colors.purple,
			pink: colors.pink,
		},
		text: {
			primary: colors.textPrimary,
			secondary: colors.textSecondary,
			disabled: colors.textDisabled,
			primaryChannel: colors.textPrimaryChannel,
			secondaryChannel: colors.textSecondaryChannel,
		},
		divider: colors.divider,
		background: {
			paper: colors.bgPaper,
			default: colors.bgDefault,
		},
		action: {
			active: colors.actionActive,
			hover: colors.actionHover,
			hoverOpacity: colors.actionHoverOpacity,
			selected: colors.actionSelected,
			selectedOpacity: colors.actionSelectedOpacity,
			disabled: colors.actionDisabled,
			disabledBackground: colors.actionDisabledBackground,
			disabledOpacity: colors.actionDisabledOpacity,
			focus: colors.actionFocus,
			focusOpacity: colors.actionFocusOpacity,
			activatedOpacity: colors.actionActivatedOpacity,
			activeChannel: colors.actionActiveChannel,
			selectedChannel: colors.actionSelectedChannel,
		},
	};
};

export default themePalette;
